version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=crmdb
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=cjugleplasctic

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=crmdb
      - DB_USER=master
      - DB_PASSWORD=cjugleplasctic

volumes:
  postgres_data:
